name: Build APK on Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the APK'
        required: false
        default: 'latest'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Node dependencies
      run: npm ci
    
    - name: Build React Vite app
      run: npm run build
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Sync Capacitor project
      run: npx cap sync android
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug
    
    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: todos-app-${{ github.event.inputs.version || 'latest' }}.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload APK to Release (if release event)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: android/app/build/outputs/apk/debug/app-debug.apk
        asset_name: todos-app.apk
        asset_content_type: application/vnd.android.package-archive